version: "3.3"
services:
  parcel:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
      
  mock-api:
    build: json-mock-api/.
    volumes:
      - ./json-mock-api:/app
    ports:
      - "3001:3000"
